meta_product_name: "dreamCo Lab"
meta_title: "dreamCo Lab - keeping hope alive."
meta_description: "dreamCo lab aims to bring hope and inspiration to hospitalized children by connecting them with creators around the world to help bring their dreams to reality.
"
meta_image: "ogimage.png" # should exist in `app/assets/images/`


